### ISSUE TITLE
Update style

### ISSUE THREAD

**Issue by devWonderkind** [Aum8/Expert-analyser#9]
heyy @Aum8 I want to add some style. please assign this issue to me.
![ss1](https://github.com/Aum8/Expert-analyser/assets/110322061/b0cb2c85-08db-4934-bd80-933a93bacce4)
Style file not link properly.

**Comment by Aum8** [comment]
Thanks for pointing it out!
I have assigned you the issue, although it seems only file name needs to be changed.
